USE master
--TWORZENIE BAZY DANYCH
GO 
IF EXISTS(
	SELECT name FROM master.dbo.sysdatabases
	WHERE name = N'BazaHotel'
	)
BEGIN
	DROP DATABASE BazaHotel
END
GO
CREATE DATABASE BazaHotel
GO
USE BazaHotel
--TWORZENIE TABEL
GO
DROP TABLE IF EXISTS dbo.Karty
GO
CREATE TABLE Karty(
[NrKarty] NCHAR(16) NOT NULL PRIMARY KEY,
[CVC] NVARCHAR(4) NOT NULL,
[DataWa¿noœci] DATE NOT NULL
)
GO
DROP TABLE IF EXISTS dbo.Klienci
GO
CREATE TABLE Klienci(
[IdKlienta] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[Imie] NVARCHAR(30) NOT NULL,
[Nazwisko] NVARCHAR(30) NOT NULL,
[Email] NVARCHAR(50) NOT NULL,
[Kraj] NVARCHAR(30) NOT NULL,
[Adres] NVARCHAR(50) NOT NULL,
[KodPocztowy] NVARCHAR(15) NOT NULL,
[Miasto] NVARCHAR(30) NOT NULL,
[Telefon] NVARCHAR(30) NOT NULL,
[NrKarty] NCHAR(16) NOT NULL
)
GO
DROP TABLE IF EXISTS dbo.Rezerwacje
GO
CREATE TABLE Rezerwacje(
[IdRezerwacji] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, --poprawka
[IdKlienta] INT NOT NULL,
[IdPokoju] INT NOT NULL,
[DataStart] DATETIME NOT NULL,
[DataStop] DATETIME NOT NULL,
[Koszt] MONEY NOT NULL,
[KosztRezygnacji] MONEY NOT NULL DEFAULT(0),--poprawka
[SposóbP³atnoœci] NVARCHAR(30) NOT NULL,
[Status] BIT NOT NULL DEFAULT(0)
)
GO
DROP TABLE IF EXISTS dbo.Pokoje
GO
CREATE TABLE Pokoje(
[IdPokoju] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[IdHotelu] INT NOT NULL,
[NrPokoju] INT NOT NULL,
[LiczbaOsób] INT NOT NULL,
[Liczba£ó¿ek] TINYINT NOT NULL,
[KosztDoba] MONEY NOT NULL,
[Status] BIT NOT NULL DEFAULT(0),
[Opis] NVARCHAR(MAX) NULL
)
GO
DROP TABLE IF EXISTS dbo.Wyposa¿enia
GO
CREATE TABLE Wyposa¿enia
(
[IdWyposa¿enia] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[IdPokoju] INT NOT NULL,
[Nazwa] NVARCHAR(30) NOT NULL
)
GO
DROP TABLE IF EXISTS dbo.Hotele
GO
CREATE TABLE Hotele(
[IdHotelu] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[Nazwa] NVARCHAR(30) NOT NULL,
[Miasto] NVARCHAR(30) NOT NULL,
[Adres] NVARCHAR(50) NOT NULL,
[Kraj] NVARCHAR(30) NOT NULL,
[Opis] NVARCHAR(MAX) NULL
)
GO
DROP TABLE IF EXISTS dbo.Udogodnienia
GO
CREATE TABLE Udogodnienia(
[IdUdogodnienia]  INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[IdHotelu] INT NOT NULL,
[Nazwa] NVARCHAR(30) NOT NULL
)
GO
